backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = Yii::$app->user->isGuest || !Yii::$app->user->can('loginToBackend') ? 'base' : 'common';

        return parent::beforeAction($action);
    }

    public function actionIndex() {
        return $this->render('index');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\models\StatisticsForm;
use Yii;
use yii\web\{Controller, Response};

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction'
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null
            ],
            'set-locale' => [
                'class' => 'common\actions\SetLocaleAction',
                'locales' => array_keys(Yii::$app->params['availableLocales'])
            ]
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string|Response
     */
    public function actionStatistics()
    {
        $model = new StatisticsForm();
        $model->load(Yii::$app->request->post());

        return $this->render('statistics/index', [
            'model' => $model
        ]);
    }
}

frontend/views/site/_item.php
<?php

use yii\helpers\{Html};
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model \common\models\Song */
/* @var $key integer */
/* @var $index integer */
/* @var $widget ListView */
?>
<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col">
                <?php
                $items = [
                    $model->title,
                    $model->album->title,
                    $model->duration,
                    Html::tag('i', '', ['class' => 'fas fa-play',]),
                ];

                echo Html::ul($items, [
                    'class' => 'list-unstyled list-group list-group-horizontal d-flex flex-column flex-sm-row ',
                    'encode' => false,
                    'itemOptions' => ['class' => 'list-group-item px-3 py-1 border-top-0 border-left-0 border-bottom-0 border-sm-0 bg-transparent rounded-0',],
                ]); ?>
            </div>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="card mb-3 text-secondary site-error mx-auto px-2 py-2">
    <div class="card-body">
        <h1><?php echo Html::encode($this->title) ?></h1>

        <div class="alert alert-danger">
            <?php echo nl2br(Html::encode($message)) ?>
        </div>

        <p>
            The above error occurred while the Web server was processing your request.
        </p>
        <p>
            Please contact us if you think this is a server error. Thank you.
        </p>
    </div>
</div>

frontend/views/site/index.php
<?php

use frontend\widgets\Ticker;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->name;
?>
<div class="site-index">
    <div class="d-flex flex-row-reverse">
        <?= Html::a(Yii::t('frontend', 'View Statistics'), ['site/statistics'], ['class' => 'btn btn-primary', 'target' => '_blank']) ;?>
    </div>
    <div class="mb-5">
        <?php echo Ticker::widget([]); ?>
    </div>
</div>